# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\muham\Documents\GitHub\valu3s_tool\ui\untitled16.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1421, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lwModelList = QtWidgets.QListView(self.centralwidget)
        self.lwModelList.setGeometry(QtCore.QRect(20, 41, 201, 301))
        self.lwModelList.setObjectName("lwModelList")
        self.lblModelID = QtWidgets.QLabel(self.centralwidget)
        self.lblModelID.setGeometry(QtCore.QRect(240, 70, 251, 31))
        self.lblModelID.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblModelID.setObjectName("lblModelID")
        self.lblFileName = QtWidgets.QLabel(self.centralwidget)
        self.lblFileName.setGeometry(QtCore.QRect(240, 110, 251, 31))
        self.lblFileName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFileName.setTextFormat(QtCore.Qt.AutoText)
        self.lblFileName.setObjectName("lblFileName")
        self.lblCreateDate = QtWidgets.QLabel(self.centralwidget)
        self.lblCreateDate.setGeometry(QtCore.QRect(240, 150, 251, 31))
        self.lblCreateDate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCreateDate.setObjectName("lblCreateDate")
        self.lblDescription = QtWidgets.QLabel(self.centralwidget)
        self.lblDescription.setGeometry(QtCore.QRect(240, 190, 251, 151))
        self.lblDescription.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblDescription.setObjectName("lblDescription")
        self.btnFromLocal = QtWidgets.QPushButton(self.centralwidget)
        self.btnFromLocal.setGeometry(QtCore.QRect(100, 350, 121, 28))
        self.btnFromLocal.setObjectName("btnFromLocal")
        self.btnSaveDataBase = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveDataBase.setGeometry(QtCore.QRect(372, 350, 121, 28))
        self.btnSaveDataBase.setObjectName("btnSaveDataBase")
        self.tabWidgetTemplates = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetTemplates.setGeometry(QtCore.QRect(510, 40, 901, 771))
        self.tabWidgetTemplates.setObjectName("tabWidgetTemplates")
        self.tabTemplate1 = QtWidgets.QWidget()
        self.tabTemplate1.setObjectName("tabTemplate1")
        self.tabWidgetTemplates.addTab(self.tabTemplate1, "")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(20, 420, 471, 391))
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetTemplates.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblModelID.setText(_translate("MainWindow", "Model ID"))
        self.lblFileName.setText(_translate("MainWindow", "File Name"))
        self.lblCreateDate.setText(_translate("MainWindow", "Create Date"))
        self.lblDescription.setText(_translate("MainWindow", "Description"))
        self.btnFromLocal.setText(_translate("MainWindow", "Open From Local"))
        self.btnSaveDataBase.setText(_translate("MainWindow", "Save To DataBase"))
        self.tabWidgetTemplates.setTabText(self.tabWidgetTemplates.indexOf(self.tabTemplate1), _translate("MainWindow", "Template 1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
