# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\muham\Documents\GitHub\valu3s_tool\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1421, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lwModelList = QtWidgets.QListView(self.centralwidget)
        self.lwModelList.setGeometry(QtCore.QRect(20, 41, 201, 301))
        self.lwModelList.setObjectName("lwModelList")
        self.wcontUPPAALDemo = QtWidgets.QStackedWidget(self.centralwidget)
        self.wcontUPPAALDemo.setGeometry(QtCore.QRect(509, 39, 901, 771))
        self.wcontUPPAALDemo.setFrameShape(QtWidgets.QFrame.Box)
        self.wcontUPPAALDemo.setObjectName("wcontUPPAALDemo")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.wcontUPPAALDemo.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.wcontUPPAALDemo.addWidget(self.page_2)
        self.lblModelID = QtWidgets.QLabel(self.centralwidget)
        self.lblModelID.setGeometry(QtCore.QRect(240, 70, 251, 31))
        self.lblModelID.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblModelID.setObjectName("lblModelID")
        self.lblFileName = QtWidgets.QLabel(self.centralwidget)
        self.lblFileName.setGeometry(QtCore.QRect(240, 110, 251, 31))
        self.lblFileName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblFileName.setObjectName("lblFileName")
        self.lblCreateDate = QtWidgets.QLabel(self.centralwidget)
        self.lblCreateDate.setGeometry(QtCore.QRect(240, 150, 251, 31))
        self.lblCreateDate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblCreateDate.setObjectName("lblCreateDate")
        self.lblDescription = QtWidgets.QLabel(self.centralwidget)
        self.lblDescription.setGeometry(QtCore.QRect(240, 190, 251, 151))
        self.lblDescription.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblDescription.setObjectName("lblDescription")
        self.btnFromLocal = QtWidgets.QPushButton(self.centralwidget)
        self.btnFromLocal.setGeometry(QtCore.QRect(100, 350, 121, 28))
        self.btnFromLocal.setObjectName("btnFromLocal")
        self.btnSaveDataBase = QtWidgets.QPushButton(self.centralwidget)
        self.btnSaveDataBase.setGeometry(QtCore.QRect(372, 350, 121, 28))
        self.btnSaveDataBase.setObjectName("btnSaveDataBase")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1421, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblModelID.setText(_translate("MainWindow", "Model ID"))
        self.lblFileName.setText(_translate("MainWindow", "File Name"))
        self.lblCreateDate.setText(_translate("MainWindow", "Create Date"))
        self.lblDescription.setText(_translate("MainWindow", "Description"))
        self.btnFromLocal.setText(_translate("MainWindow", "Open From Local"))
        self.btnSaveDataBase.setText(_translate("MainWindow", "Save To DataBase"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
